"""
scons build file

@author: Jean-Lou Dupont
"""
import os
import sys
import shutil

Help("""\
 Type:	
   'scons' to build the program,
""")

env = Environment(CPPFLAGS="-D_DEBUG -g")
Program('test',  Glob("src/test.c"),  LIBS=['litm_debug', 'pthread'] )
       
Program('test2', Glob("src/test2.c"), LIBS=['litm_debug', 'pthread'] )

#Program('test3', Glob("src/test3.c"), LIBS=['litm_debug', 'pthread'] )

Program('test3', Glob("src/test3.c"), LIBS=['litm_debug', 'pthread'] )

Program('test4', Glob("src/test4.c"), LIBS=['litm_debug', 'pthread'] )

Program('test5', Glob("src/test5.c"), LIBS=['litm_debug', 'pthread'] )

Program('test6', Glob("src/test6.c"), LIBS=['litm_debug', 'pthread'] )
