LITM: project/src/connection.c File Reference
project/src/connection.c File Reference
#include <pthread.h>
#include <errno.h>
#include "litm.h"
#include "connection.h"
#include "queue.h"
#include "logger.h"
Functions
int __litm_connection_get_index (litm_connection *(table)[], litm_connection *conn)
int __litm_connection_get_free_index (litm_connection *(table)[])
litm_connection * __litm_connection_get_ptr (int connection_index)
int litm_connection_get_id (litm_connection *conn)
litm_code litm_connection_open (litm_connection **conn)
litm_code litm_connection_open_ex (litm_connection **conn, int id)
litm_code litm_connection_close (litm_connection *conn)
void _litm_connections_lock (void)
int _litm_connections_trylock (void)
void _litm_connections_unlock (void)
int _litm_connection_validate (litm_connection *conn)
int _litm_connection_validate_safe (litm_connection *conn)
void _litm_connection_lock (litm_connection *conn)
void _litm_connection_unlock (litm_connection *conn)
litm_connection_status _litm_connection_get_status (litm_connection *conn)
Variables
pthread_mutex_t _connections_mutex = PTHREAD_MUTEX_INITIALIZER
litm_connection * _connections [LITM_CONNECTION_MAX]
pthread_mutex_t _connections_pending_deletion_mutex = PTHREAD_MUTEX_INITIALIZER
litm_connection * _connections_pending_deletion [LITM_CONNECTION_MAX]
Detailed Description
Date:
2009-04-24
Author:
Jean-Lou Dupont
This module implements the ``connection`` aspect:
opening
closing
A limited number of connections are supported at any point in time. When a connection is closed, it is queued for later deletion: the connection can not be used for any access from this point onwards.
From a client operation point of view, the connection table is only locked whilst performing:
``open`` and ``close`` connection operations
``add`` and ``remove`` subscription operations
at which times the return code LITM_CODE_BUSY might be used to signal to the client to try again later. This behavior is necessary in order for the ``switch`` to be in control position, thus simplifying the architecture and API.
Since the ``switch`` is in control, the connection table is also held in locked state whilst dispatching envelopes to clients.
Connection deletion is performed in the following manner:
the connection's status is changed to "PENDING_DELETION"
the connection identifier is placed in a stack (pending deletion)
the ``switch`` inspects the said stack at regular interval
Definition in file connection.c.
Function Documentation
int __litm_connection_get_free_index (litm_connection * (table)[])
Verifies if a `spot` is available in the connection map OR -1 if none.
Definition at line 218 of file connection.c.
References LITM_CONNECTION_MAX.
Referenced by litm_connection_close(), and litm_connection_open_ex().
int __litm_connection_get_index (litm_connection * (table)[], litm_connection * conn)
Definition at line 196 of file connection.c.
References LITM_CONNECTION_MAX.
litm_connection * __litm_connection_get_ptr (int connection_index)
Definition at line 187 of file connection.c.
References LITM_CONNECTION_MAX.
litm_connection_status _litm_connection_get_status (litm_connection * conn)
Definition at line 303 of file connection.c.
References _litm_connection::status.
void _litm_connection_lock (litm_connection * conn)
Definition at line 290 of file connection.c.
References _litm_connection::input_queue, and queue::mutex.
void _litm_connection_unlock (litm_connection * conn)
Definition at line 297 of file connection.c.
References _litm_connection::input_queue, and queue::mutex.
int _litm_connection_validate (litm_connection * conn)
See also:
_litm_connection_validate_safe
Definition at line 256 of file connection.c.
References _litm_connection_validate_safe(), _litm_connections_trylock(), and _litm_connections_unlock().
int _litm_connection_validate_safe (litm_connection * conn)
Connection validation
Returns:
0 => not active
1 => active
Definition at line 276 of file connection.c.
References LITM_CONNECTION_MAX.
Referenced by _litm_connection_validate().
void _litm_connections_lock (void)
Definition at line 233 of file connection.c.
int _litm_connections_trylock (void)
Definition at line 239 of file connection.c.
Referenced by _litm_connection_validate(), switch_add_subscriber(), and switch_remove_subscriber().
void _litm_connections_unlock (void)
Definition at line 246 of file connection.c.
Referenced by _litm_connection_validate(), switch_add_subscriber(), and switch_remove_subscriber().
litm_code litm_connection_close (litm_connection * conn)
Closes an opened connection
Definition at line 155 of file connection.c.
References __litm_connection_get_free_index(), DEBUG_LOG, LITM_CODE_ERROR_BAD_CONNECTION, LITM_CODE_ERROR_NO_MORE_CONNECTIONS, LITM_CODE_OK, LITM_CONNECTION_STATUS_PENDING_DELETION, and _litm_connection::status.
Referenced by litm_disconnect().
int litm_connection_get_id (litm_connection * conn)
Returns the connection id
Returns:
-1 on error
Definition at line 83 of file connection.c.
References _litm_connection::id.
litm_code litm_connection_open (litm_connection ** conn)
Opens a ``connection``
Definition at line 97 of file connection.c.
References litm_connection_open_ex().
litm_code litm_connection_open_ex (litm_connection ** conn, int id)
Definition at line 105 of file connection.c.
References __litm_connection_get_free_index(), LITM_CODE_BUSY, LITM_CODE_ERROR_MALLOC, LITM_CODE_ERROR_NO_MORE_CONNECTIONS, LITM_CODE_OK, LITM_CONNECTION_STATUS_ACTIVE, queue_create(), and _litm_connection::received.
Referenced by litm_connect_ex(), and litm_connection_open().
Variable Documentation
litm_connection* _connections[LITM_CONNECTION_MAX]
Definition at line 66 of file connection.c.
pthread_mutex_t _connections_mutex = PTHREAD_MUTEX_INITIALIZER
Definition at line 65 of file connection.c.
litm_connection* _connections_pending_deletion[LITM_CONNECTION_MAX]
Definition at line 71 of file connection.c.
pthread_mutex_t _connections_pending_deletion_mutex = PTHREAD_MUTEX_INITIALIZER
Definition at line 70 of file connection.c.