LITM: project/includes/litm.h File Reference
project/includes/litm.h File Reference
#include <sys/types.h>
#include <pthread.h>
Data Structures
struct _queue_node
struct queue
struct _litm_connection
struct __litm_routing
struct _litm_envelope
Defines
#define LITM_CONNECTION_MAX 15
#define LITM_BUSSES_MAX 7
#define LITM_DEFAULT_MAX_TIMEOUT 5
#define LITM_DEFAULT_MAX_BACKOFF 1
Typedefs
typedef struct _queue_node queue_node
typedef int litm_bus
typedef enum
_litm_connection_status_codes litm_connection_status
typedef struct _litm_connection litm_connection
typedef enum _litm_codes litm_code
typedef struct _litm_envelope litm_envelope
Enumerations
enum _litm_connection_status_codes { LITM_CONNECTION_STATUS_INVALID = 0, LITM_CONNECTION_STATUS_ACTIVE, LITM_CONNECTION_STATUS_PENDING_DELETION }
enum _litm_codes {
LITM_CODE_OK = 0, LITM_CODE_NO_MESSAGE, LITM_CODE_BUSY, LITM_CODE_ERROR_MALLOC,
LITM_CODE_ERROR_CONNECTION_OPEN, LITM_CODE_ERROR_BAD_CONNECTION, LITM_CODE_ERROR_NO_MORE_CONNECTIONS, LITM_CODE_ERROR_INVALID_BUS,
LITM_CODE_ERROR_SWITCH_SENDER_EQUAL_CURRENT, LITM_CODE_ERROR_SWITCH_NO_CURRENT, LITM_CODE_ERROR_SWITCH_NEXT_NOT_FOUND, LITM_CODE_ERROR_OUTPUT_QUEUING,
LITM_CODE_BUSY_OUTPUT_QUEUE, LITM_CODE_ERROR_INVALID_ENVELOPE, LITM_CODE_ERROR_SUBSCRIPTION_NOT_FOUND, LITM_CODE_ERROR_BUS_FULL,
LITM_CODE_BUSY_CONNECTIONS, LITM_CODE_ERROR_CONNECTION_NOT_ACTIVE, LITM_CODE_ERROR_END_OF_SUBSCRIBERS_LIST, LITM_CODE_ERROR_NO_SUBSCRIBERS,
LITM_CODE_ERROR_CONNECTION_ERROR, LITM_CODE_ERROR_SUBSCRIPTION_ERROR, LITM_CODE_ERROR_SEND_ERROR, LITM_CODE_ERROR_RECEIVE_WAIT
}
Functions
litm_code litm_connect (litm_connection **conn)
litm_code litm_connect_ex (litm_connection **conn, int id)
litm_code litm_connect_ex_wait (litm_connection **conn, int id, int timeout)
int litm_connection_get_id (litm_connection *conn)
litm_code litm_disconnect (litm_connection *conn)
litm_code litm_subscribe (litm_connection *conn, litm_bus bus_id)
litm_code litm_subscribe_wait (litm_connection *conn, litm_bus bus_id, int timeout)
litm_code litm_unsubscribe (litm_connection *conn, litm_bus bus_id)
litm_code litm_send (litm_connection *conn, litm_bus bus_id, void *msg, void(*cleaner)(void *msg))
litm_code litm_send_wait (litm_connection *conn, litm_bus bus_id, void *msg, void(*cleaner)(void *msg), int timeout)
litm_code litm_send_shutdown (litm_connection *conn, litm_bus bus_id, void *msg, void(*cleaner)(void *msg))
void litm_wait_shutdown (void)
litm_code litm_receive_nb (litm_connection *conn, litm_envelope **envlp)
litm_code litm_receive_wait (litm_connection *conn, litm_envelope **envlp)
litm_code litm_release (litm_connection *conn, litm_envelope *envlp)
void * litm_get_message (litm_envelope *envlp)
char * litm_translate_code (litm_code code)
Detailed Description
Version:
$version
Date:
2009-04-24
Author:
Jean-Lou Dupont
Definition in file litm.h.
Define Documentation
#define LITM_BUSSES_MAX 7
Definition at line 205 of file litm.h.
Referenced by __switch_init_tables(), switch_add_subscriber(), switch_remove_subscriber(), switch_send(), and switch_send_shutdown().
#define LITM_CONNECTION_MAX 15
Definition at line 204 of file litm.h.
Referenced by __litm_connection_get_free_index(), __litm_connection_get_index(), __litm_connection_get_ptr(), __switch_find_match(), __switch_init_tables(), _litm_connection_validate_safe(), switch_add_subscriber(), and switch_remove_subscriber().
#define LITM_DEFAULT_MAX_BACKOFF 1
Definition at line 207 of file litm.h.
Referenced by litm_connect_ex_wait(), litm_send_wait(), and litm_subscribe_wait().
#define LITM_DEFAULT_MAX_TIMEOUT 5
Definition at line 206 of file litm.h.
Referenced by __litm_compute_timeout().
Typedef Documentation
typedef int litm_bus
``Bus`` identifier type
Definition at line 243 of file litm.h.
typedef enum _litm_codes litm_code
typedef struct _litm_connection litm_connection
``Connection`` type
Parameters:
input_queue the connection's input queue
typedef enum _litm_connection_status_codes litm_connection_status
``Connection Status`` type
typedef struct _litm_envelope litm_envelope
``Envelope`` structure for messages
Parameters:
cleaner The ``cleaner`` function to use
routes The ``routing`` structure
msg The pointer to the message
Contains the pointer to the message as well as a ``routing`` structure used to deliver the said message to all bus which have at least 1 subscriber.
The client (ie. receiver of the envelope) must not tamper with the message (ie. msg) as it is shared with other client(s).
typedef struct _queue_node queue_node
Queue node - entry in a queue
Parameters:
msg,: pointer to the message
next,: pointer to the ``next`` queue_node entry
Enumeration Type Documentation
enum _litm_codes
Enumerator:
LITM_CODE_OK
LITM_CODE_NO_MESSAGE
LITM_CODE_BUSY
LITM_CODE_ERROR_MALLOC
LITM_CODE_ERROR_CONNECTION_OPEN
LITM_CODE_ERROR_BAD_CONNECTION
LITM_CODE_ERROR_NO_MORE_CONNECTIONS
LITM_CODE_ERROR_INVALID_BUS
LITM_CODE_ERROR_SWITCH_SENDER_EQUAL_CURRENT
LITM_CODE_ERROR_SWITCH_NO_CURRENT
LITM_CODE_ERROR_SWITCH_NEXT_NOT_FOUND
LITM_CODE_ERROR_OUTPUT_QUEUING
LITM_CODE_BUSY_OUTPUT_QUEUE
LITM_CODE_ERROR_INVALID_ENVELOPE
LITM_CODE_ERROR_SUBSCRIPTION_NOT_FOUND
LITM_CODE_ERROR_BUS_FULL
LITM_CODE_BUSY_CONNECTIONS
LITM_CODE_ERROR_CONNECTION_NOT_ACTIVE
LITM_CODE_ERROR_END_OF_SUBSCRIBERS_LIST
LITM_CODE_ERROR_NO_SUBSCRIBERS
LITM_CODE_ERROR_CONNECTION_ERROR
LITM_CODE_ERROR_SUBSCRIPTION_ERROR
LITM_CODE_ERROR_SEND_ERROR
LITM_CODE_ERROR_RECEIVE_WAIT
Definition at line 292 of file litm.h.
enum _litm_connection_status_codes
``Connection Status`` type
Enumerator:
LITM_CONNECTION_STATUS_INVALID
LITM_CONNECTION_STATUS_ACTIVE
LITM_CONNECTION_STATUS_PENDING_DELETION
Definition at line 248 of file litm.h.
Function Documentation
litm_code litm_connect (litm_connection ** conn)
Opens a ``connection`` to the ``switch`` and returns a pointer to the connection reference
Parameters:
**conn pointer to connection reference
Definition at line 55 of file litm.c.
References litm_connect_ex().
litm_code litm_connect_ex (litm_connection ** conn, int id)
Opens a ``connection`` to the ``switch`` and returns a pointer to the connection reference
See also:
litm_connect
Parameters:
**conn pointer to connection reference
id connection identifier
Definition at line 61 of file litm.c.
References DEBUG_LOG, LITM_CODE_OK, litm_connection_open_ex(), and switch_init().
Referenced by litm_connect(), and litm_connect_ex_wait().
litm_code litm_connect_ex_wait (litm_connection ** conn, int id, int timeout)
Opens a ``connection`` to the ``switch`` and returns a pointer to the connection reference. Waits for a maximum of ``timeout``.
See also:
litm_connect
Parameters:
**conn pointer to connection reference
id connection identifier
timeout timeout in seconds, 0 for the default
Definition at line 77 of file litm.c.
References __litm_compute_timeout(), DEBUG_LOG, LITM_CODE_BUSY, LITM_CODE_ERROR_CONNECTION_ERROR, LITM_CODE_OK, litm_connect_ex(), LITM_DEFAULT_MAX_BACKOFF, and random_sleep_period().
int litm_connection_get_id (litm_connection * conn)
Returns the connection associated with a valid connection
Returns:
-1 on error
Returns the connection id
Returns:
-1 on error
Definition at line 83 of file connection.c.
References _litm_connection::id.
litm_code litm_disconnect (litm_connection * conn)
Disconnects from the ``switch``
Once a client calls this function, no more access with the connection is permitted to any of the following functions:
litm_subscribe
litm_unsubscribe
litm_receive_nb
litm_send
litm_release
Be sure to release any message in the client's care before disconnecting.
Parameters:
*conn connection reference
Definition at line 112 of file litm.c.
References litm_connection_close().
void* litm_get_message (litm_envelope * envlp)
Returns a copy of the pointer to the message.
Parameters:
*envlp the envelope from which to extract the pointer to the message
This function should be used instead of relying on the ``litm_envelope`` data structure.
** DO NOT** modify the message!
Definition at line 312 of file litm.c.
References _litm_envelope::msg.
litm_code litm_receive_nb (litm_connection * conn, litm_envelope ** envlp)
Receives (non-blocking) from any ``bus``
See also:
litm_disconnect
Parameters:
*conn connection reference
**envlp the pointer to received envelope
Receive (non-blocking) function for clients
Note:
It is the responsibility of the client to _not_ use this function once a connection is closed.
Definition at line 236 of file litm.c.
References _litm_connection::input_queue, LITM_CODE_ERROR_BAD_CONNECTION, LITM_CODE_NO_MESSAGE, LITM_CODE_OK, queue_get_nb(), and _litm_connection::received.
litm_code litm_receive_wait (litm_connection * conn, litm_envelope ** envlp)
Receives (waiting) from any ``bus``
See also:
litm_disconnect
Parameters:
*conn connection reference
**envlp the pointer to received envelope
Receive with wait
Definition at line 257 of file litm.c.
References DEBUG_LOG, _litm_connection::input_queue, LITM_CODE_ERROR_BAD_CONNECTION, LITM_CODE_ERROR_RECEIVE_WAIT, LITM_CODE_OK, queue_get_nb(), queue_wait(), and _litm_connection::received.
litm_code litm_release (litm_connection * conn, litm_envelope * envlp)
Releases an ``envelope``
See also:
litm_disconnect
Parameters:
*conn connection reference
*envlp the pointer to received envelope to release
Once the client has consumed the message ``contained`` in the envelope, the client **MUST** release it back to litm.
Release a message to LITM
This function should *ONLY* be used by client's as a result of finishing the processing of an envelope/message retrieved through ``litm_receive_nb''.
Definition at line 305 of file litm.c.
References switch_release().
litm_code litm_send (litm_connection * conn, litm_bus bus_id, void * msg, void(*)(void *msg) cleaner)
Send message on a ``bus``
See also:
litm_disconnect
Parameters:
*conn connection reference
bus_id the ``bus`` to send the message onto
*msg the pointer to the message
*cleaner the pointer to the cleaner function
If omitted, the default ``cleaner`` function will be free().
If an error occurs, it is the responsibility of the sender to dispose of the ``messages`` appropriately. If the operation went LITM_CODE_OK, then once all recipients are finished with the message, the ``cleaner`` will be called with the message pointer OR if ``cleaner`` is NULL, the message will simply be freed with free().
Definition at line 168 of file litm.c.
References switch_send().
litm_code litm_send_shutdown (litm_connection * conn, litm_bus bus_id, void * msg, void(*)(void *msg) cleaner)
Send message on a _bus_ and shutdown
Sends the message around to the subscribers and once the message has been released by the last subscriber, performs a shutdown of the switch thread.
Each client subscriber is responsible for recognizing the message (since litm does not interpret client messages) and terminate its access to litm & terminates its threads.
See also:
litm_send
Parameters:
*conn connection reference
bus_id the ``bus`` to send the message onto
*msg the pointer to the message
*cleaner the pointer to the cleaner function
Definition at line 219 of file litm.c.
References switch_send_shutdown().
litm_code litm_send_wait (litm_connection * conn, litm_bus bus_id, void * msg, void(*)(void *msg) cleaner, int timeout)
See also:
litm_send_wait
Definition at line 178 of file litm.c.
References __litm_compute_timeout(), DEBUG_LOG, _litm_connection::id, LITM_CODE_BUSY, LITM_CODE_ERROR_SEND_ERROR, LITM_CODE_OK, LITM_DEFAULT_MAX_BACKOFF, random_sleep_period(), and switch_send().
litm_code litm_subscribe (litm_connection * conn, litm_bus bus_id)
Subscribe to a ``bus``
See also:
litm_disconnect
Parameters:
*conn connection reference
bus_id the ``bus`` identifier to subscribe to
Definition at line 119 of file litm.c.
References switch_add_subscriber().
litm_code litm_subscribe_wait (litm_connection * conn, litm_bus bus_id, int timeout)
See also:
litm_subscribe
Definition at line 126 of file litm.c.
References __litm_compute_timeout(), DEBUG_LOG, LITM_CODE_BUSY, LITM_CODE_ERROR_SUBSCRIPTION_ERROR, LITM_CODE_OK, LITM_DEFAULT_MAX_BACKOFF, random_sleep_period(), and switch_add_subscriber().
char* litm_translate_code (litm_code code)
Translates a code to a message pointer
Parameters:
code a litm_code to translate to a string version
Definition at line 322 of file litm.c.
References LITM_CODE_MESSAGES.
Referenced by __switch_handle_pending(), and __switch_thread_function().
litm_code litm_unsubscribe (litm_connection * conn, litm_bus bus_id)
Unsubscribe from a ``bus``
See also:
litm_disconnect
Parameters:
*conn connection reference
bus_id the ``bus`` identifier to unsubscribe from
Definition at line 162 of file litm.c.
References switch_remove_subscriber().
void litm_wait_shutdown (void)
Definition at line 354 of file litm.c.
References __switch_wait_shutdown().