LITM: project/src/queue.c File Reference
project/src/queue.c File Reference
#include <pthread.h>
#include <errno.h>
#include "logger.h"
#include "litm.h"
#include "queue.h"
Functions
void * __queue_get_safe (queue *q)
int queue_put_head_safe (queue *q, void *node)
int queue_put_safe (queue *q, void *node)
queue * queue_create (int id)
void queue_destroy (queue *q)
int queue_put (queue *q, void *node)
int queue_put_nb (queue *q, void *node)
int queue_put_wait (queue *q, void *node)
void * queue_get (queue *q)
void * queue_get_nb (queue *q)
int queue_wait (queue *q)
int queue_wait_timer (queue *q, int usec_timer)
int queue_peek (queue *q)
void queue_signal (queue *q)
int queue_put_head_nb (queue *q, void *node)
int queue_put_head (queue *q, void *node)
int queue_put_head_wait (queue *q, void *node)
Detailed Description
Date:
2009-04-24
Author:
: Jean-Lou Dupont
The _queue_ module isn't aware of its elements and thus it is the responsibility of the clients to properly dispose of the _nodes_ once retrieved.
The term ``node`` is used generically to refer to a node element inside a queue.
Definition in file queue.c.
Function Documentation
void * __queue_get_safe (queue * q)
Definition at line 399 of file queue.c.
References DEBUG_LOG, queue::head, queue::id, _queue_node::next, _queue_node::node, queue::num, queue::tail, queue::total_in, and queue::total_out.
Referenced by queue_get(), and queue_get_nb().
queue* queue_create (int id)
Creates a queue
Definition at line 35 of file queue.c.
References queue::cond, DEBUG_LOG, queue::head, queue::id, queue::mutex, queue::num, queue::tail, queue::total_in, and queue::total_out.
Referenced by litm_connection_open_ex(), and switch_init().
void queue_destroy (queue * q)
Destroys a queue
This function is **not** aware of the message(s) potentially inside the queue, thus, the queue must be drained **before** using this function.
The queue can be drained by:
stopping the thread that ``puts``
``getting`` until NULL is returned
Definition at line 90 of file queue.c.
References queue::cond, DEBUG_LOG, and queue::mutex.
void* queue_get (queue * q)
Retrieves the next node from a queue
Returns:
NULL if none.
Definition at line 276 of file queue.c.
References __queue_get_safe(), DEBUG_LOG, and queue::mutex.
void* queue_get_nb (queue * q)
Retrieves the next node from a queue (non-blocking)
Returns:
NULL => No node OR BUSY
Definition at line 299 of file queue.c.
References __queue_get_safe(), DEBUG_LOG, and queue::mutex.
Referenced by __switch_thread_function(), litm_receive_nb(), litm_receive_wait(), and litm_receive_wait_timer().
int queue_peek (queue * q)
Verifies if a message is present
Returns:
1 if at least 1 message is present,
0 if NONE
-1 on ERROR
Definition at line 453 of file queue.c.
References DEBUG_LOG, queue::head, and queue::mutex.
int queue_put (queue * q, void * node)
Queues a node (blocking)
Returns:
1 => success
0 => error
Definition at line 119 of file queue.c.
References queue::cond, DEBUG_LOG, queue::mutex, and queue_put_safe().
Referenced by __switch_safe_send(), __switch_thread_function(), __switch_try_sending_or_requeue(), and switch_release().
int queue_put_head (queue * q, void * node)
Puts a node at the HEAD of the queue
This function is meant to support _high priority_ messages.
Parameters:
q queue reference
node message reference
Returns:
1 => success
0 => error
Definition at line 531 of file queue.c.
References queue::cond, DEBUG_LOG, queue::mutex, and queue_put_head_safe().
Referenced by __switch_safe_send().
int queue_put_head_nb (queue * q, void * node)
Queues a node at the HEAD (non-blocking)
Returns:
1 => success
0 => error
-1 => busy
Definition at line 500 of file queue.c.
References queue::cond, DEBUG_LOG, queue::mutex, and queue_put_head_safe().
int queue_put_head_safe (queue * q, void * msg)
Puts a node a the HEAD of the queue without regards to thread-safety
Returns:
1 SUCCESS
0 ERROR
Definition at line 616 of file queue.c.
References queue::head, _queue_node::next, _queue_node::node, queue::num, queue::tail, and queue::total_in.
Referenced by queue_put_head(), queue_put_head_nb(), and queue_put_head_wait().
int queue_put_head_wait (queue * q, void * node)
Queue Put Head Wait
Returns:
0 ERROR
1 SUCCESS
Definition at line 560 of file queue.c.
References queue::cond, DEBUG_LOG, queue::mutex, and queue_put_head_safe().
Referenced by __switch_try_sending_to_recipient().
int queue_put_nb (queue * q, void * node)
Queues a node (non-blocking)
Returns:
1 => success
0 => error
-1 => busy
Definition at line 149 of file queue.c.
References queue::cond, DEBUG_LOG, queue::mutex, and queue_put_safe().
Referenced by __switch_try_sending_to_recipient().
int queue_put_safe (queue * q, void * node)
Queue_put_safe
Lock is not handled here - the caller must take care of this.
Returns:
0 => error
1 => success
Definition at line 232 of file queue.c.
References queue::head, _queue_node::next, _queue_node::node, queue::num, queue::tail, and queue::total_in.
Referenced by queue_put(), queue_put_nb(), and queue_put_wait().
int queue_put_wait (queue * q, void * node)
Queue Put Wait
Returns:
0 ERROR
1 SUCCESS
Definition at line 177 of file queue.c.
References queue::cond, DEBUG_LOG, queue::mutex, and queue_put_safe().
void queue_signal (queue * q)
Definition at line 477 of file queue.c.
References queue::cond, DEBUG_LOG, and queue::mutex.
Referenced by _litm_connection_signal_all(), and switch_release().
int queue_wait (queue * q)
Waits for a node in the queue
Returns:
0 SUCCESS
1 FAILURE
Definition at line 326 of file queue.c.
References queue::cond, DEBUG_LOG, and queue::mutex.
Referenced by __switch_thread_function(), and litm_receive_wait().
int queue_wait_timer (queue * q, int usec_timer)
Wait but with timeout
Returns:
0 SUCCESS
1 FAILURE
Definition at line 362 of file queue.c.
References queue::cond, DEBUG_LOG, queue::id, and queue::mutex.
Referenced by litm_receive_wait_timer().