LITM: project/includes/switch.h File Reference
project/includes/switch.h File Reference
#include <pthread.h>
Functions
int switch_init (void)
void * switch_thread_function (void *params)
litm_code switch_add_subscriber (litm_connection *conn, litm_bus bus_id)
litm_code switch_remove_subscriber (litm_connection *conn, litm_bus bus_id)
litm_code switch_send (litm_connection *conn, litm_bus bus_id, void *msg, void(*cleaner)(void *msg))
litm_code switch_send_shutdown (litm_connection *conn, litm_bus bus_id, void *msg, void(*cleaner)(void *msg))
litm_code switch_release (litm_connection *conn, litm_envelope *envlp)
void __switch_wait_shutdown (void)
Detailed Description
Date:
2009-04-25
Author:
Jean-Lou Dupont
Definition in file switch.h.
Function Documentation
void __switch_wait_shutdown (void)
Wait for shutdown
Once a litm_send_shutdowm is used, this function should be called to neatly shutdown the process.
Definition at line 100 of file switch.c.
References _switchThread.
Referenced by litm_wait_shutdown().
litm_code switch_add_subscriber (litm_connection * conn, litm_bus bus_id)
Definition at line 482 of file switch.c.
References _litm_connections_trylock(), _litm_connections_unlock(), _subscribers_mutex, DEBUG_LOG, LITM_BUSSES_MAX, LITM_CODE_BUSY, LITM_CODE_ERROR_BAD_CONNECTION, LITM_CODE_ERROR_BUS_FULL, LITM_CODE_ERROR_INVALID_BUS, LITM_CODE_OK, and LITM_CONNECTION_MAX.
Referenced by litm_subscribe(), and litm_subscribe_wait().
int switch_init (void)
Definition at line 68 of file switch.c.
References __switch_init_tables(), __switch_thread_function(), _switchThread, _switchThread_status, DEBUG_LOG, and queue_create().
Referenced by litm_connect_ex().
litm_code switch_release (litm_connection * conn, litm_envelope * envlp)
A client has finished processing a message: send it through through the ``input_queue`` and if all intended recipients have processed it already, it will be finalized.
Definition at line 344 of file switch.c.
References __switch_finalize(), DEBUG_LOG, _litm_connection::id, LITM_CODE_ERROR_BAD_CONNECTION, LITM_CODE_ERROR_INVALID_ENVELOPE, LITM_CODE_ERROR_MALLOC, LITM_CODE_OK, queue_put(), queue_signal(), _litm_connection::released, _litm_envelope::released_count, and _litm_envelope::routes.
Referenced by litm_release().
litm_code switch_remove_subscriber (litm_connection * conn, litm_bus bus_id)
Definition at line 521 of file switch.c.
References _litm_connections_trylock(), _litm_connections_unlock(), _subscribers_mutex, LITM_BUSSES_MAX, LITM_CODE_BUSY, LITM_CODE_ERROR_BAD_CONNECTION, LITM_CODE_ERROR_INVALID_BUS, LITM_CODE_ERROR_SUBSCRIPTION_NOT_FOUND, LITM_CODE_OK, and LITM_CONNECTION_MAX.
Referenced by litm_unsubscribe().
litm_code switch_send (litm_connection * conn, litm_bus bus_id, void * msg, void(*)(void *msg) cleaner)
This function just queues up the message in the switch's input_queue without actually sending it to recipients.
This function blocks whilst accessing the switch's ``input_queue`` but no deadlock scenario is possible since the switch's thread does not block whilst dequeuing.
Definition at line 588 of file switch.c.
References __switch_safe_send(), LITM_BUSSES_MAX, LITM_CODE_ERROR_BAD_CONNECTION, LITM_CODE_ERROR_INVALID_BUS, and LITM_SHUTDOWN_FLAG_FALSE.
Referenced by litm_send(), and litm_send_wait().
litm_code switch_send_shutdown (litm_connection * conn, litm_bus bus_id, void * msg, void(*)(void *msg) cleaner)
See also:
switch_send
Definition at line 564 of file switch.c.
References __switch_safe_send(), LITM_BUSSES_MAX, LITM_CODE_ERROR_BAD_CONNECTION, LITM_CODE_ERROR_INVALID_BUS, and LITM_SHUTDOWN_FLAG_TRUE.
Referenced by litm_send_shutdown().
void* switch_thread_function (void * params)