LITM: project/includes/utils.h File Reference
project/includes/utils.h File Reference
#include <sys/time.h>
Functions
void random_sleep (int max_usecs)
int random_sleep_period (struct timeval *start, struct timeval *current, int max_usecs_interval, int max_usecs_total)
Detailed Description
Date:
2009-05-13
Author:
Jean-Lou Dupont
Definition in file utils.h.
Function Documentation
void random_sleep (int max_usecs)
Sleeps for a random period of time up to a maximum of ``max_usecs``
Parameters:
max_usecs maximum sleep in microseconds
Definition at line 15 of file utils.c.
Referenced by random_sleep_period().
int random_sleep_period (struct timeval * start, struct timeval * current, int max_usecs_interval, int max_usecs_total)
Random Interval based sleeping
This function ''sleeps'' for a maximum of ``max_usecs_total`` in intervals of ``max_usecs_interval`` at the time.
Parameters:
start the start time
current the current time
max_usecs_interval maximum sleep per interval
max_usecs_total maximum total sleep
Returns:
0 SUCCESS
1 End of Period
Definition at line 25 of file utils.c.
References random_sleep().
Referenced by litm_connect_ex_wait(), litm_send_wait(), and litm_subscribe_wait().