LITM: project/includes/connection.h File Reference
project/includes/connection.h File Reference
Functions
litm_code litm_connection_open (litm_connection **conn)
litm_code litm_connection_open_ex (litm_connection **conn, int id)
litm_code litm_connection_close (litm_connection *conn)
void _litm_connections_lock (void)
void _litm_connections_unlock (void)
int _litm_connections_trylock (void)
int _litm_connection_validate (litm_connection *conn)
int _litm_connection_validate_safe (litm_connection *conn)
void _litm_connection_lock (litm_connection *conn)
void _litm_connection_unlock (litm_connection *conn)
litm_connection_status _litm_connection_get_status (litm_connection *conn)
Detailed Description
Date:
2009-04-24
Author:
Jean-Lou Dupont
Definition in file connection.h.
Function Documentation
litm_connection_status _litm_connection_get_status (litm_connection * conn)
Definition at line 303 of file connection.c.
References _litm_connection::status.
void _litm_connection_lock (litm_connection * conn)
Definition at line 290 of file connection.c.
References _litm_connection::input_queue, and queue::mutex.
void _litm_connection_unlock (litm_connection * conn)
Definition at line 297 of file connection.c.
References _litm_connection::input_queue, and queue::mutex.
int _litm_connection_validate (litm_connection * conn)
See also:
_litm_connection_validate_safe
Definition at line 256 of file connection.c.
References _litm_connection_validate_safe(), _litm_connections_trylock(), and _litm_connections_unlock().
int _litm_connection_validate_safe (litm_connection * conn)
Connection validation
Returns:
0 => not active
1 => active
Definition at line 276 of file connection.c.
References LITM_CONNECTION_MAX.
Referenced by _litm_connection_validate().
void _litm_connections_lock (void)
Definition at line 233 of file connection.c.
int _litm_connections_trylock (void)
Definition at line 239 of file connection.c.
Referenced by _litm_connection_validate(), switch_add_subscriber(), and switch_remove_subscriber().
void _litm_connections_unlock (void)
Definition at line 246 of file connection.c.
Referenced by _litm_connection_validate(), switch_add_subscriber(), and switch_remove_subscriber().
litm_code litm_connection_close (litm_connection * conn)
Closes an opened connection
Definition at line 155 of file connection.c.
References __litm_connection_get_free_index(), DEBUG_LOG, LITM_CODE_ERROR_BAD_CONNECTION, LITM_CODE_ERROR_NO_MORE_CONNECTIONS, LITM_CODE_OK, LITM_CONNECTION_STATUS_PENDING_DELETION, and _litm_connection::status.
Referenced by litm_disconnect().
litm_code litm_connection_open (litm_connection ** conn)
Opens (creates) a new connection
Opens a ``connection``
Definition at line 97 of file connection.c.
References litm_connection_open_ex().
litm_code litm_connection_open_ex (litm_connection ** conn, int id)
Definition at line 105 of file connection.c.
References __litm_connection_get_free_index(), LITM_CODE_BUSY, LITM_CODE_ERROR_MALLOC, LITM_CODE_ERROR_NO_MORE_CONNECTIONS, LITM_CODE_OK, LITM_CONNECTION_STATUS_ACTIVE, queue_create(), and _litm_connection::received.
Referenced by litm_connect_ex(), and litm_connection_open().