LITM: project/includes/pool.h File Reference
project/includes/pool.h File Reference
Defines
#define LITM_POOL_SIZE 128
Functions
void __litm_pool_recycle (litm_envelope *envlp)
litm_envelope * __litm_pool_get (void)
void __litm_pool_destroy (litm_envelope *envlp)
void __litm_pool_clean (litm_envelope *envlp)
Detailed Description
Date:
2009-04-24
Author:
Jean-Lou Dupont
Definition in file pool.h.
Define Documentation
#define LITM_POOL_SIZE 128
Definition at line 12 of file pool.h.
Referenced by __litm_pool_get(), and __litm_pool_recycle().
Function Documentation
void __litm_pool_clean (litm_envelope * envlp)
Clean-up an ``envelope`` for reuse
Cleans an ``envelope``
NOTE: use with care i.e. the ``msg`` member is just NULLed.
Definition at line 164 of file pool.c.
References _litm_envelope::cleaner, _litm_envelope::delivery_count, _litm_envelope::msg, _litm_envelope::released_count, _litm_envelope::routes, and _litm_envelope::shutdown_flag.
Referenced by __litm_pool_get().
void __litm_pool_destroy (litm_envelope * envlp)
Destroys an ``envelope``
(probably because we have no more place on the stack)
Destroys an ``envelope`` ie. just use free()
A client of this module **must** dispose of the internal structure of the ``envelope`` (ie. the ``msg`` member) before using this function.
Definition at line 144 of file pool.c.
References DEBUG_LOG.
Referenced by __litm_pool_recycle().
litm_envelope* __litm_pool_get (void)
Gets an ``envelope`` from the pool or creates a new one
Retrieves an ``envelope`` from either:
the stack if one is available
the heap
Either case, the ``envelope`` is initialized before returning it to the client.
Definition at line 81 of file pool.c.
References __litm_pool_clean(), _created, _pool_mutex, _returned, _stack_initialized, _top_stack, and LITM_POOL_SIZE.
Referenced by __switch_safe_send().
void __litm_pool_recycle (litm_envelope * envlp)
Recycles an ``envelope``
NOTE: We only keep up to LITM_POOL_SIZE ----- messages in the stack.
Recyles an ``envelope`` by either:
putting it on a stack for later recall
destroying it if there is no more place on the stack
NOTE: it is the responsibility of the client of this module to dispose of properly of the internal structure (ie. the ``msg`` member) of the ``envelope`` **before** using this recycling facility.
Definition at line 47 of file pool.c.
References __litm_pool_destroy(), _pool_mutex, _recycled, _top_stack, and LITM_POOL_SIZE.
Referenced by __switch_finalize(), and __switch_safe_send().