LITM: project/includes/queue.h File Reference
project/includes/queue.h File Reference
#include <stdlib.h>
#include <unistd.h>
#include <pthread.h>
#include "litm.h"
Functions
queue * queue_create (int id)
void queue_destroy (queue *queue)
int queue_put_nb (queue *q, void *msg)
int queue_put (queue *q, void *msg)
int queue_put_wait (queue *q, void *node)
int queue_put_head_nb (queue *q, void *node)
int queue_put_head (queue *q, void *msg)
int queue_put_head_wait (queue *q, void *node)
void * queue_get (queue *q)
void * queue_get_nb (queue *q)
int queue_wait (queue *q)
int queue_peek (queue *q)
void queue_signal (queue *q)
Detailed Description
Date:
2009-04-23
Author:
Jean-Lou Dupont
Note:
The definition of the types for this module are located in litm.h
Definition in file queue.h.
Function Documentation
queue* queue_create (int id)
Creates a queue
Definition at line 35 of file queue.c.
References queue::cond, queue::cond_mutex, DEBUG_LOG, queue::head, queue::id, queue::mutex, queue::num, queue::tail, queue::total_in, and queue::total_out.
Referenced by litm_connection_open_ex(), and switch_init().
void queue_destroy (queue * q)
Destroys a queue
This function is **not** aware of the message(s) potentially inside the queue, thus, the queue must be drained **before** using this function.
The queue can be drained by:
stopping the thread that ``puts``
``getting`` until NULL is returned
Definition at line 99 of file queue.c.
References queue::cond, queue::cond_mutex, DEBUG_LOG, and queue::mutex.
void* queue_get (queue * q)
Retrieves the next node from a queue
Returns:
NULL if none.
Definition at line 283 of file queue.c.
References __queue_get_safe(), DEBUG_LOG, and queue::mutex.
void* queue_get_nb (queue * q)
Retrieves the next node from a queue (non-blocking)
Returns:
NULL => No node OR BUSY
Definition at line 306 of file queue.c.
References __queue_get_safe(), DEBUG_LOG, and queue::mutex.
Referenced by __switch_thread_function(), litm_receive_nb(), and litm_receive_wait().
int queue_peek (queue * q)
Verifies if a message is present
Returns:
1 if at least 1 message is present,
0 if NONE
-1 on ERROR
Definition at line 414 of file queue.c.
References DEBUG_LOG, queue::head, and queue::mutex.
int queue_put (queue * q, void * node)
Queues a node (blocking)
Returns:
1 => success
0 => error
Definition at line 130 of file queue.c.
References queue::cond, DEBUG_LOG, queue::mutex, and queue_put_safe().
Referenced by __switch_thread_function(), and switch_release().
int queue_put_head (queue * q, void * node)
Puts a node at the HEAD of the queue
This function is meant to support _high priority_ messages.
Parameters:
q queue reference
node message reference
Returns:
1 => success
0 => error
Definition at line 487 of file queue.c.
References queue::cond, DEBUG_LOG, queue::mutex, and queue_put_head_safe().
Referenced by __switch_try_sending_or_requeue().
int queue_put_head_nb (queue * q, void * node)
Queues a node at the HEAD (non-blocking)
Returns:
1 => success
0 => error
-1 => busy
Definition at line 456 of file queue.c.
References queue::cond, DEBUG_LOG, queue::mutex, and queue_put_head_safe().
Referenced by __switch_safe_send().
int queue_put_head_wait (queue * q, void * node)
Queue Put Head Wait
Returns:
0 ERROR
1 SUCCESS
Definition at line 517 of file queue.c.
References queue::cond, queue::cond_mutex, DEBUG_LOG, queue::id, queue::mutex, and queue_put_head_safe().
Referenced by __switch_try_sending_to_recipient().
int queue_put_nb (queue * q, void * node)
Queues a node (non-blocking)
Returns:
1 => success
0 => error
-1 => busy
Definition at line 160 of file queue.c.
References queue::cond, DEBUG_LOG, queue::mutex, and queue_put_safe().
Referenced by __switch_safe_send(), and __switch_try_sending_to_recipient().
int queue_put_wait (queue * q, void * node)
Queue Put Wait
Returns:
0 ERROR
1 SUCCESS
Definition at line 188 of file queue.c.
References queue::cond, queue::cond_mutex, DEBUG_LOG, queue::mutex, and queue_put_safe().
void queue_signal (queue * q)
Definition at line 438 of file queue.c.
References queue::cond, and DEBUG_LOG.
Referenced by switch_release().
int queue_wait (queue * q)
Waits for a node in the queue
Returns:
0 SUCCESS
1 FAILURE
Definition at line 333 of file queue.c.
References queue::cond, queue::cond_mutex, and DEBUG_LOG.
Referenced by litm_receive_wait().