LITM: project/src/switch.c File Reference
project/src/switch.c File Reference
#include <stdlib.h>
#include <pthread.h>
#include <errno.h>
#include <sys/types.h>
#include "litm.h"
#include "switch.h"
#include "queue.h"
#include "pool.h"
#include "connection.h"
#include "logger.h"
Defines
#define LITM_SHUTDOWN_FLAG_TRUE 1
#define LITM_SHUTDOWN_FLAG_FALSE 0
Functions
void * __switch_thread_function (void *params)
litm_code __switch_get_next_subscriber (litm_connection **result, int *result_index, litm_connection *sender, int current, litm_bus bus_id)
int __switch_find_match (litm_connection *sender, int ref, litm_bus bus_id)
litm_code __switch_try_sending_to_recipient (litm_connection *recipient, litm_envelope *env)
litm_code __switch_finalize (litm_envelope *envlp)
litm_code __switch_try_sending_or_requeue (litm_connection *conn, litm_envelope *envlp)
void __switch_init_tables (void)
void __switch_handle_pending (litm_envelope *e)
litm_code __switch_safe_send (litm_connection *conn, litm_bus bus_id, void *msg, void(*cleaner)(void *msg), int shutdown_flag)
litm_connection * __switch_index_to_connection (int bus_id, int index)
int switch_init (void)
void __switch_wait_shutdown (void)
litm_code switch_release (litm_connection *conn, litm_envelope *envlp)
litm_code switch_add_subscriber (litm_connection *conn, litm_bus bus_id)
litm_code switch_remove_subscriber (litm_connection *conn, litm_bus bus_id)
litm_code switch_send_shutdown (litm_connection *conn, litm_bus bus_id, void *msg, void(*cleaner)(void *msg))
litm_code switch_send (litm_connection *conn, litm_bus bus_id, void *msg, void(*cleaner)(void *msg))
Variables
queue * _switch_queue
pthread_t _switchThread
int _switchThread_status = 0
pthread_mutex_t _subscribers_mutex = PTHREAD_MUTEX_INITIALIZER
litm_connection * _subscribers [LITM_BUSSES_MAX][LITM_CONNECTION_MAX+1]
Detailed Description
Date:
2009-04-25
Author:
Jean-Lou Dupont
This source implements the *switch* function whereby *envelopes* are presented, turn-wise, to each recipient(s) subscribing to a particular *bus*.
Definition in file switch.c.
Define Documentation
#define LITM_SHUTDOWN_FLAG_FALSE 0
Definition at line 28 of file switch.c.
Referenced by __switch_safe_send(), __switch_thread_function(), __switch_try_sending_to_recipient(), and switch_send().
#define LITM_SHUTDOWN_FLAG_TRUE 1
Definition at line 27 of file switch.c.
Referenced by __switch_safe_send(), __switch_thread_function(), __switch_try_sending_to_recipient(), and switch_send_shutdown().
Function Documentation
litm_code __switch_finalize (litm_envelope * envlp)
Finalizes a message contained in an envelope & recycles the envelope
Definition at line 689 of file switch.c.
References __litm_pool_recycle(), _litm_envelope::cleaner, DEBUG_LOG, LITM_CODE_ERROR_INVALID_ENVELOPE, LITM_CODE_OK, and _litm_envelope::msg.
Referenced by __switch_handle_pending(), __switch_thread_function(), and switch_release().
int __switch_find_match (litm_connection * sender, int ref, litm_bus bus_id)
Find ``match``
THIS FUNCTION IS NOT *CONNECTION SAFE* and thus must be called whilst holding the _connections lock.
Definition at line 787 of file switch.c.
References LITM_CONNECTION_MAX.
Referenced by __switch_get_next_subscriber().
litm_code __switch_get_next_subscriber (litm_connection ** result, int * result_index, litm_connection * sender, int current, litm_bus bus_id)
Scans the subscription map for the subscriber that follows ``current``. If ``current`` is NULL (thus indicating the start of the scan), then pull the first subscriber from the subscription to bus ``bus_id``.
Furthermore, we are implementing ``split horizon`` forwarding ie. don't send the message back to the originator.
If end of list is reached, return NULL.
CASES: ======
1- empty subscription list 2- single subscriber a) the sender b) other subscriber 3- more than 1 subscriber
Definition at line 735 of file switch.c.
References __switch_find_match(), LITM_CODE_ERROR_END_OF_SUBSCRIBERS_LIST, and LITM_CODE_OK.
Referenced by __switch_thread_function().
void __switch_handle_pending (litm_envelope * e)
Handle ``pending`` requests to sent
Definition at line 292 of file switch.c.
References __switch_finalize(), __switch_try_sending_or_requeue(), DEBUG_LOG, LITM_CODE_BUSY_CONNECTIONS, LITM_CODE_BUSY_OUTPUT_QUEUE, LITM_CODE_ERROR_BAD_CONNECTION, LITM_CODE_OK, litm_translate_code(), and _litm_envelope::routes.
Referenced by __switch_thread_function().
litm_connection * __switch_index_to_connection (int bus_id, int index)
Definition at line 809 of file switch.c.
void __switch_init_tables (void)
Definition at line 84 of file switch.c.
References LITM_BUSSES_MAX, and LITM_CONNECTION_MAX.
Referenced by switch_init().
litm_code __switch_safe_send (litm_connection * conn, litm_bus bus_id, void * msg, void(*)(void *msg) cleaner, int shutdown_flag)
Definition at line 603 of file switch.c.
References __litm_pool_get(), __litm_pool_recycle(), _litm_envelope::cleaner, _litm_envelope::delivery_count, LITM_CODE_BUSY, LITM_CODE_ERROR_MALLOC, LITM_CODE_OK, LITM_SHUTDOWN_FLAG_FALSE, LITM_SHUTDOWN_FLAG_TRUE, _litm_envelope::msg, queue_put_head_nb(), queue_put_nb(), _litm_envelope::released_count, _litm_envelope::requeued, _litm_envelope::routes, _litm_connection::sent, and _litm_envelope::shutdown_flag.
Referenced by switch_send(), and switch_send_shutdown().
void * __switch_thread_function (void * params)
The switch thread dequeues messages from the ``input queue`` and dispatches them to the next connection queue.
Definition at line 111 of file switch.c.
References __switch_finalize(), __switch_get_next_subscriber(), __switch_handle_pending(), __switch_try_sending_or_requeue(), DEBUG_LOG, _litm_connection::id, LITM_CODE_BUSY_CONNECTIONS, LITM_CODE_BUSY_OUTPUT_QUEUE, LITM_CODE_ERROR_CONNECTION_NOT_ACTIVE, LITM_CODE_ERROR_END_OF_SUBSCRIBERS_LIST, LITM_CODE_OK, LITM_SHUTDOWN_FLAG_FALSE, LITM_SHUTDOWN_FLAG_TRUE, litm_translate_code(), queue_get_nb(), queue_put(), _litm_envelope::routes, and _litm_envelope::shutdown_flag.
Referenced by switch_init().
litm_code __switch_try_sending_or_requeue (litm_connection * conn, litm_envelope * envlp)
Tries sending the envelope along BUT requeue if this is not possible at this juncture.
The call to __switch_try_sending_to_recipient is connection safe.
Definition at line 385 of file switch.c.
References __switch_try_sending_to_recipient(), _litm_envelope::delivery_count, LITM_CODE_BUSY_OUTPUT_QUEUE, LITM_CODE_ERROR_CONNECTION_NOT_ACTIVE, LITM_CODE_ERROR_INVALID_ENVELOPE, LITM_CODE_OK, queue_put_head(), _litm_envelope::requeued, and _litm_envelope::routes.
Referenced by __switch_handle_pending(), and __switch_thread_function().
litm_code __switch_try_sending_to_recipient (litm_connection * conn, litm_envelope * env)
Try sending the message to the recipient.
This function does not block waiting for the recipient. This function should only be called by ''__switch_try_sending_or_requeue''.
Definition at line 426 of file switch.c.
References DEBUG_LOG, _litm_connection::input_queue, LITM_CODE_BUSY_OUTPUT_QUEUE, LITM_CODE_ERROR_BAD_CONNECTION, LITM_CODE_ERROR_CONNECTION_NOT_ACTIVE, LITM_CODE_ERROR_INVALID_ENVELOPE, LITM_CODE_ERROR_OUTPUT_QUEUING, LITM_CODE_OK, LITM_SHUTDOWN_FLAG_FALSE, LITM_SHUTDOWN_FLAG_TRUE, queue_put_head_wait(), queue_put_nb(), _litm_envelope::routes, and _litm_envelope::shutdown_flag.
Referenced by __switch_try_sending_or_requeue().
void __switch_wait_shutdown (void)
Wait for shutdown
Once a litm_send_shutdowm is used, this function should be called to neatly shutdown the process.
Definition at line 99 of file switch.c.
References _switchThread.
Referenced by litm_wait_shutdown().
litm_code switch_add_subscriber (litm_connection * conn, litm_bus bus_id)
Definition at line 481 of file switch.c.
References _litm_connections_trylock(), _litm_connections_unlock(), _subscribers_mutex, LITM_BUSSES_MAX, LITM_CODE_BUSY, LITM_CODE_ERROR_BAD_CONNECTION, LITM_CODE_ERROR_BUS_FULL, LITM_CODE_ERROR_INVALID_BUS, LITM_CODE_OK, and LITM_CONNECTION_MAX.
Referenced by litm_subscribe(), and litm_subscribe_wait().
int switch_init (void)
Definition at line 67 of file switch.c.
References __switch_init_tables(), __switch_thread_function(), _switchThread, _switchThread_status, and queue_create().
Referenced by litm_connect_ex().
litm_code switch_release (litm_connection * conn, litm_envelope * envlp)
A client has finished processing a message: send it through through the ``input_queue`` and if all intended recipients have processed it already, it will be finalized.
Definition at line 343 of file switch.c.
References __switch_finalize(), DEBUG_LOG, LITM_CODE_ERROR_BAD_CONNECTION, LITM_CODE_ERROR_INVALID_ENVELOPE, LITM_CODE_ERROR_MALLOC, LITM_CODE_OK, queue_put(), queue_signal(), _litm_connection::released, _litm_envelope::released_count, and _litm_envelope::routes.
Referenced by litm_release().
litm_code switch_remove_subscriber (litm_connection * conn, litm_bus bus_id)
Definition at line 520 of file switch.c.
References _litm_connections_trylock(), _litm_connections_unlock(), _subscribers_mutex, LITM_BUSSES_MAX, LITM_CODE_BUSY, LITM_CODE_ERROR_BAD_CONNECTION, LITM_CODE_ERROR_INVALID_BUS, LITM_CODE_ERROR_SUBSCRIPTION_NOT_FOUND, LITM_CODE_OK, and LITM_CONNECTION_MAX.
Referenced by litm_unsubscribe().
litm_code switch_send (litm_connection * conn, litm_bus bus_id, void * msg, void(*)(void *msg) cleaner)
This function just queues up the message in the switch's input_queue without actually sending it to recipients.
This function blocks whilst accessing the switch's ``input_queue`` but no deadlock scenario is possible since the switch's thread does not block whilst dequeuing.
Definition at line 587 of file switch.c.
References __switch_safe_send(), LITM_BUSSES_MAX, LITM_CODE_ERROR_BAD_CONNECTION, LITM_CODE_ERROR_INVALID_BUS, and LITM_SHUTDOWN_FLAG_FALSE.
Referenced by litm_send(), and litm_send_wait().
litm_code switch_send_shutdown (litm_connection * conn, litm_bus bus_id, void * msg, void(*)(void *msg) cleaner)
See also:
switch_send
Definition at line 563 of file switch.c.
References __switch_safe_send(), LITM_BUSSES_MAX, LITM_CODE_ERROR_BAD_CONNECTION, LITM_CODE_ERROR_INVALID_BUS, and LITM_SHUTDOWN_FLAG_TRUE.
Referenced by litm_send_shutdown().
Variable Documentation
litm_connection* _subscribers[LITM_BUSSES_MAX][LITM_CONNECTION_MAX+1]
Definition at line 40 of file switch.c.
pthread_mutex_t _subscribers_mutex = PTHREAD_MUTEX_INITIALIZER
Definition at line 39 of file switch.c.
Referenced by switch_add_subscriber(), and switch_remove_subscriber().
queue* _switch_queue
Definition at line 31 of file switch.c.
pthread_t _switchThread
Definition at line 34 of file switch.c.
Referenced by __switch_wait_shutdown(), and switch_init().
int _switchThread_status = 0
Definition at line 35 of file switch.c.
Referenced by switch_init().